/**
 * 🎬 Recorded transformPoint fixtures
 * Generated by running app with VITE_OPENCV_RECORD_MODE=true
 * These are real transformation outputs from OpenCV homography calculations
 */

export const transformPointFixtures = [
  {
    input: {
      x: 218.02,
      y: 215.47,
      inverse: false
    },
    output: {
      x: 1180.22,
      y: 901.99
    }
  },
  {
    input: {
      x: 248.75,
      y: 221.82,
      inverse: false
    },
    output: {
      x: 1252.69,
      y: 918.87
    }
  },
  {
    input: {
      x: 189.43,
      y: 301.92,
      inverse: false
    },
    output: {
      x: 1002.69,
      y: 1112.67
    }
  },
  {
    input: {
      x: 189.19,
      y: 300.01,
      inverse: false
    },
    output: {
      x: 1004.31,
      y: 1107.85
    }
  }
];
